name: Docs

on: [push, pull_request]


defaults:
  run:
    shell: bash -l {0}
jobs:
  build_docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: dev-environment.yml
      - name: Install
        run: python -m pip install -v .[docs]
      - name: Build
        run: make -C docs html
      - name: Publish
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          force_orphan: true
