name: Publish Package

on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        channels: conda-forge
        environment-file: false
        environment-name: ipympl-release
        extra-specs: |
          python=3.9
          jupyterlab
          yarn
          matplotlib
          ipywidgets
          jupyter-packaging=0.7

    - name: Install dependencies
      run: |
        python -m pip install twine wheel build

    - name: Publish the Python package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m build
        twine upload dist/ipympl-*

    - name: Publish the NPM package
      run: |
        jlpm install && jlpm build
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        PRE_RELEASE: ${{ github.event.release.prerelease }}
