name: Publish Package
permissions:
  contents: read

on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Install Conda environment with Micromamba
      uses: mamba-org/setup-micromamba@b09ef9b599704322748535812ca03efb2625677b # v2
      with:
        environment-name: ipympl-release
        create-args: >-
          python=3.12
          yarn
          ipywidgets
          jupyterlab

    - name: Install dependencies
      run: |
        python -m pip install twine wheel build "packaging>=24.2"

    - name: Publish the Python package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m build
        twine upload dist/ipympl-*

    - name: Publish the NPM package
      run: |
        jlpm install && jlpm build
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        PRE_RELEASE: ${{ github.event.release.prerelease }}
